### ISSUE TITLE
dtiestim 1.2.0 and option to shift negative eigenvalues  not working for IDWI

### ISSUE THREAD

**Issue by rachelsteiner** [NIRALUser/DTIProcessToolkit#3]
Hi NIRALUser,
dtiestim 1.2.0 's new option to shift negative eigenvalues works well for B0 and DTI images but it is  not working for IDWI (not correcting the tensors). Neither  DWIToDTIEstimation in 3DSlicer nor dtiestim 1.2.0's shiftNeg feature provides for a corrected IDWI image. Is there an alternative solution to creating the IDWI image with correct information? 

Thanks,
rachel

**Comment by fbudin69500** [comment]
Hello Rachel,
IDWI anb B0 images do not contain tensors. Therefore the option provided by dtiestim to shift the negative eigenvalues is  unable to correct your images. If you mean that your output IDWI images contain NaN value, I suggest you look into ImageMath (which is part of https://github.com/NIRALUser/niral_utilities) which provides an option ("-NaNCor") to remove NaN values.
Hope that helps,

Francois
