### ISSUE TITLE
Rotationally invariant scalars are computed from negative eigenvalues

### ISSUE THREAD

**Issue by aghayoor** [NIRALUser/DTIProcessToolkit#4]
In DTI estimation, diffusion tensors are formally in the form of symmetric positive semidefinite square (3x3) matrices.
All the scalars derived from DTI assumes use of lambada1 >= lambada2 >= lambada3 >= 0 to refer to the eigenvalues of the symmetric positive semidefinite diffusion tensor D.

However, the presence of noise in DWI images does not guarantee that the estimated symmetric tensors are always positive semidefinite.
The following paper shows the probability of obtaining negative eigenvalues as a function of lambda1/lambda3 for the ‘rice’ shaped diffusion tensor at different noise levels (%1 to %5):
http://www.sciencedirect.com/science/article/pii/S0730725X00001533

It shows that negative values happen more likely with increasing noise. Some solutions are suggested in this regard:
-- Calculate rotationally scalar values (RISs) with negative eigenvalues reset to zero.
-- Spatial smoothing of DWI image.
-- Temporal smoothing of DWI image with repeat experiments.
-- Calculate D by limiting D to be positive semidefinite matrix, e.g. this paper: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2791793/

Based on the assumption of lambada1 >= lambada2 >= lambada3 >= 0, all RIS images computed by DTIProcess (FA, MD, RD, Frobenus_norm, Lambda1, Lambda2, Lambda3) should have all non-negative values.
However, the presence of negative values are seen in the computation of MD, RD and Lambda{1,2,3} images.

In the attached test program, I have shown the negative scalar measures corresponding to a sample diffusion tensor value:

double x[6] = {-0.00179759,-8.98788e-05,4.40478e-05,-0.00192165,-4.54233e-05,0.00191396};

DTIProcess uses “vnl_symmetric_eigensystem_compute_eigenvals” function from vnl to compute eigenvalues:
http://public.kitware.com/vxl/doc/development/core/vnl/html/vnl__symmetric__eigensystem_8h.html

vnl_symmetric_eigensystem_compute_eigenvals(
                                              x[0], x[1], x[2],
                                              x[3], x[4],
                                              x[5],
                                              lambdas[0],
                                              lambdas[1],
                                              lambdas[2]);

This function sorts the resulting eigenvalues in “increasing" order, so lambda[0] is the smallest eigenvalues. Printing lambdas to the screen results in:

std::cout << "Lambda = " << lambdas[0] << "," << lambdas[1] << "," << lambdas[2] << std::endl;

Lambda = -0.00196893, -0.0017514, 0.00191505

Therefore, DTIProcess uses above measured eigenvalues to fill in the computed voxel in Lambda{1,2,3} images:
Lambda1 = 0.00191505
Lambda2 = -0.0017514
Lambda3 = -0.00196893

In addition to have negative values for Lambda2 and Lambda3, the magnitude of computed Lambda3 is greater than the magnitude of Lambda1:  |Lambda3| > |Lambda1|.
Definitely, it is an issue in current implementation of the program.

My suggested approach to address this issue is to use singular values instead of eigenvalues.

The singular value decomposition for symmetric matrices results in non-negative singular values that have the same magnitude as the eigenvalues:
http://math.stackexchange.com/questions/22825/how-to-compute-svd-singular-value-decomposition-of-a-symmetric-matrix

“The SVD for a symmetric matrix A=UΣVT, where U and V are unitary matrices with U=[u1|u2|…|un], V=[v1|v2|…|vn] and Σ is a diagonal matrix with non-negative diagonal entries and vi=±ui"

In my example, I used “vnl_svd” function to compute SVD for the sample diffusion tensor:
http://public.kitware.com/vxl/doc/release/core/vnl/html/classvnl__svd.html

vnl_matrix<double> Tensor(3,3);
  Tensor[0][0]=x[0];
  Tensor[0][1]=x[1];
  Tensor[0][2]=x[2];
  Tensor[1][0]=x[1];
  Tensor[1][1]=x[3];
  Tensor[1][2]=x[4];
  Tensor[2][0]=x[2];
  Tensor[2][1]=x[4];
  Tensor[2][2]=x[5];
  
typedef vnl_svd<double> MatrixSVDType;
MatrixSVDType svd(Tensor);

The DiagMatrix W stores the singular values in “decreasing" order, so in analogy with printing lambda[0], lambda[1] and lambda[2]:

std::cout << "Lambda = " << svd.W(2) << "," << svd.W(1) << "," << svd.W(0) << std::endl;

Lambda = 0.0017514, 0.00191505, 0.00196893

Therefore, DTIProcess fills in values of the Lambda{1,2,3} images in the compute voxel as:
Lambda1 = 0.00196893
Lambda2 = 0.00191505
Lambda3 = 0.0017514

As seen, the order of lambda1 to lambda3 is like when we sort the outputs eigenvalues of “ vnl_symmetric_eigensystem_compute_eigenvals” function based on their absolute value.
Therefore, there are two possible ways to modify the current code:

1) Compute the eigenvalues based on the “ vnl_symmetric_eigensystem_compute_eigenvals” function, and “sort” them based on their absolute value:

  double lambdas[3];
  // The resulting eigenvectors and values are sorted in increasing order, so
  // lambdas[0] is the smallest eigenvalue.
  vnl_symmetric_eigensystem_compute_eigenvals(x[0], x[1], x[2],
                                              x[3], x[4],
                                              x[5],
                                              lambdas[0],
                                              lambdas[1],
                                              lambdas[2]);
  // Now we order them based on magnitude
  std::transform(lambdas, lambdas+3, lambdas, std::abs<double>);
  std::sort(lambdas, lambdas+3);

2) Inser the Tensor values in a vnl_matrix and compute the SVD of this matrix using “vnl_svd”:

vnl_matrix<double> Tensor(3,3);
  Tensor[0][0]=x[0];
  Tensor[0][1]=x[1];
  Tensor[0][2]=x[2];
  Tensor[1][0]=x[1];
  Tensor[1][1]=x[3];
  Tensor[1][2]=x[4];
  Tensor[2][0]=x[2];
  Tensor[2][1]=x[4];
  Tensor[2][2]=x[5];
  
typedef vnl_svd<double> MatrixSVDType;
MatrixSVDType svd(Tensor);

To decide which method will be used to modify the code, I used “itkTimeProb.h” to compare the run time of each of above methods on my system. My results show that the first solution in on average 3.5 times faster. Therefore, I used the first method.
Please see the attached test program for more detail.

The other bug in current implementation of DTI process, is the way MD (mean diffusivity) is computed.
Currently, MD is computed by invoking the trace from the “itkDiffusionTensor3D” class:

  typedef itk::DiffusionTensor3D<double>::AccumulateValueType   AccumulateValueType;
  AccumulateValueType trace = x[0];
  trace += x[3];
  trace += x[5];
  std::cout << "Compute MD by current version of DTIProcess: " << trace/3.0 << std::endl;

Compute MD by current version of DTIProcess: -0.00060176

The trace of a matrix is equal to sum of its eigenvalues:
http://math.stackexchange.com/questions/546155/proof-that-the-trace-of-a-matrix-is-the-sum-of-its-eigenvalues

Therefore, based on the above implementation, the MD is computed from the negative eigenvalues.
Following shows the results when we use the singular values (absolute values of eigenvalues) for MD computation, that is completely different than the above value:

std::cout << "Corrected value for MD: " << (lambdas[0]+lambdas[1]+lambdas[2])/3.0 << std::endl;

Corrected value for MD: 0.00187846

I have made a new patch that makes proper modifications to the code to address above issues.

**Comment by aghayoor** [comment]
![screen shot 2015-04-26 at 12 59 54 pm](https://cloud.githubusercontent.com/assets/926354/7338541/4964d2c0-ec14-11e4-9fef-55b510508c0f.png)

**Comment by aghayoor** [comment]
The following patch is created to address above issues:
https://github.com/aghayoor/DTIProcessToolkit/commit/45bf98d5286b4bc998604e1caf3ad4ba0d0e41a8

**Comment by aghayoor** [comment]
@hjmjohnson : Please check this out!

**Comment by styner** [comment]
I am fine with supporting SVD for eigenvalue computation. Important though that this should not replace the current functionality (DTIProcess offers other ways to correct data with negative eigenvalues), but rather should be added (otherwise it's not transparent to users of the new version using SVD). 

This is not a bug fix, but rather a feature that's being added. So, it's great you are doing this, but don't treat it as a bug.

The dtiprocess application should allow users to select either one. We can discuss which should be used by default (I suggest the old version for compatibility, but I am okay with using the SVD computation by default if it's sufficiently tested).

**Comment by hjmjohnson** [comment]
@styner Martin,  Should we have a T-Con to discuss?  Would you like us to work directly with someone on your team?

**Comment by styner** [comment]
May be best. I'd be happy to join and so is Francois (I talked to him)

**Comment by hjmjohnson** [comment]
@styner @fbudin69500 @aghayoor 

Martin would 30 minutes during one of the following times work for you:
Tomorrow Wednesday: 10:30am-1:00pm
                     Thursday: 10:00am-2:00pm
                          Friday: 10:30am-1:30pm

**Comment by styner** [comment]
I can do thursday at 10am or 11am (east coast time). Rest is already booked.
Martin

**Comment by hjmjohnson** [comment]
@styner @fbudin69500 @aghayoor 

I sent a calendar invitation for a GoTo meeting T-Con at 11am EST (10am CST).

**Comment by fbudin69500** [comment]
That works for me too. I haven't received the GoTo meeting invitation though.

**Comment by hjmjohnson** [comment]
@fbudin69500 @styner The calendar invite should have contained the goto meeting information,

Here it is:
1.  Please join my meeting, Apr 30, 2015 at 10:00 AM CDT.
https://global.gotomeeting.com/join/228939421

2.  Use your microphone and speakers (VoIP) - a headset is recommended. Or, call in using your telephone.

Dial +1 (872) 240-3212
Access Code: 228-939-421
Audio PIN: Shown after joining the meeting

Meeting ID: 228-939-421

GoToMeeting®
Online Meetings Made Easy®

Not at your computer? Click the link to join this meeting from your iPhone®, iPad®, Android® or Windows Phone® device via the GoToMeeting app.

**Comment by hjmjohnson** [comment]
Code updated to include features from DTIReg that allow nearest PSD matrix to be computed.
