### ISSUE TITLE
Tensor Estimation Correct to ensure that the root cause of negative eigenvalues is addressed.

### ISSUE THREAD

**Issue by hjmjohnson** [NIRALUser/DTIProcessToolkit#5]
Propogate tensor correction from https://github.com/NIRALUser/ResampleDTIlogEuclidean/blob/master/Source/ResampleDTI.xml

to DTIProcess code.

  <string-enumeration>
      <name>correction</name>
      <longflag>--correction</longflag>
      <description>Correct the tensors if computed tensor is not semi-definite positive. Useful only if nolog is selected</description>
      <label>Tensors Correction</label>
      <element>zero</element>
      <element>none</element>
      <element>abs</element>
      <element>nearest</element>
      <default>none</default>
    </string-enumeration>
</parameters>

=======================
Verify that the code adheres to the computations defined in

Computing a nearest symmetric positive semidefinite matrix
Nicholas J. Higham
Under an Elsevier user license
 Show more
doi:10.1016/0024-3795(88)90223-6

Extend the ShareLatex document.

**Comment by hjmjohnson** [comment]
@aghayoor

Please review this.

**Comment by aghayoor** [comment]
3 new patches are added, and a new pull request is sent:
https://github.com/NIRALUser/DTIProcessToolkit/pull/6

**Comment by hjmjohnson** [comment]
Issues addressed and code updated.  All tests pass.
